general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ['shell-exec %userprofile%/.glzr/zebar/start.bat']

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'window_focus'

gaps:
  # Gap between adjacent windows.
  inner_gap: '2px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '40px'
    right: '5px'
    bottom: '5px'
    left: '5px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#8dbcff'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
    display_name: '[1] Alpha'
  - name: "2"
    display_name: '[2] Bravo'
  - name: "3"
    display_name: '[3] Charlie'
  - name: "4"
    display_name: '[4] Delta'
  - name: "5"
    display_name: '[5] Echo'
  - name: "6"
    display_name: '[6] Foxtrot'
  - name: "7"
    display_name: '[7] Golf'
  - name: "8"
    display_name: '[8] Hotel'
  - name: "9"
    display_name: '[9] India'
  - name: "10"
    display_name: '[10] Juliet'
  - name: "11"
    display_name: '[11] Kilo'
  - name: "12"
    display_name: '[12] Lima'
  - name: "13"
    display_name: '[13] Mike'
  - name: "14"
    display_name: '[14] November'
  - name: "15"
    display_name: '[15] Oscar'
  - name: "16"
    display_name: '[16] Papa'
  - name: "17"
    display_name: '[17] Quebec'
  - name: "18"
    display_name: '[18] Romeo'
  - name: "19"
    display_name: '[19] Sierra'
  - name: "20"
    display_name: '[20] Tango'

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys.PowerAccent' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+oem_minus']
  - commands: ['resize --width +2%']
    bindings: ['alt+oem_plus']
  - commands: ['resize --height +2%']
    bindings: ['alt+shift+oem_plus']
  - commands: ['resize --height -2%']
    bindings: ['alt+shift+oem_minus']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+x']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+f']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+f']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+shift+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+g']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --next-workspace']
    bindings: ['alt+b']
  - commands: ['focus --prev-workspace']
    bindings: ['alt+v']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+y']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 7']
    bindings: ['alt+c']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']
  - commands: ['focus --workspace 10']
    bindings: ['alt+0']
  - commands: ['focus --workspace 11']
    bindings: ['alt+insert+1']
  - commands: ['focus --workspace 12']
    bindings: ['alt+insert+2']
  - commands: ['focus --workspace 13']
    bindings: ['alt+insert+3']
  - commands: ['focus --workspace 14']
    bindings: ['alt+insert+4']
  - commands: ['focus --workspace 15']
    bindings: ['alt+insert+5']
  - commands: ['focus --workspace 16']
    bindings: ['alt+insert+6']
  - commands: ['focus --workspace 17']
    bindings: ['alt+insert+7']
  - commands: ['focus --workspace 18']
    bindings: ['alt+insert+8']
  - commands: ['focus --workspace 19']
    bindings: ['alt+insert+9']
  - commands: ['focus --workspace 20']
    bindings: ['alt+insert+0']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['alt+left']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+right']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+up']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+down']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+c']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']
  - commands: ['move --workspace 10', 'focus --workspace 10']
    bindings: ['alt+shift+0']
  - commands: ['move --workspace 11', 'focus --workspace 11']
    bindings: ['alt+insert+shift+1']
  - commands: ['move --workspace 12', 'focus --workspace 12']
    bindings: ['alt+insert+shift+2']
  - commands: ['move --workspace 13', 'focus --workspace 13']
    bindings: ['alt+insert+shift+3']
  - commands: ['move --workspace 14', 'focus --workspace 14']
    bindings: ['alt+insert+shift+4']
  - commands: ['move --workspace 15', 'focus --workspace 15']
    bindings: ['alt+insert+shift+5']
  - commands: ['move --workspace 16', 'focus --workspace 16']
    bindings: ['alt+insert+shift+6']
  - commands: ['move --workspace 17', 'focus --workspace 17']
    bindings: ['alt+insert+shift+7']
  - commands: ['move --workspace 18', 'focus --workspace 18']
    bindings: ['alt+insert+shift+8']
  - commands: ['move --workspace 19', 'focus --workspace 19']
    bindings: ['alt+insert+shift+9']
  - commands: ['move --workspace 20', 'focus --workspace 20']
    bindings: ['alt+insert+shift+0']
